openapi: 3.0.3
info:
  title: Cinema API
  description: "Cinema API for Administrator to
  * create cinema
  * create halls at cinema
  * create tariff
  * tariff plan id with prices to tariff
  * describe seats at hall with tariff plan id"
  version: 1.0.0
  contact:
    name: Mikhail Gaidamaka
    url: https://github.com/mgaidamak
    email: magnoly.nsk@gmail.com
servers:
  - url: 'https'
paths:
  /cinema:
    post:
      tags:
      - cinema
      - admin
      summary: Create new cinema
      description: Create new cinema
      operationId: createCinema
      requestBody:
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/Cinema'
      responses:
        200:
          description: Cinema has been created
  /cinema/{id}:
    get:
      tags:
      - cinema
      - admin
      summary: Get cinema by ID
      description: Get cinema by ID
      operationId: getCinemaById
      parameters:
      - name: id
        in: path
        description: ID of cinema
        required: true
        schema: 
          type: integer
          format: int64
      responses:
        200:
          description: Cinema found
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Cinema'
        404:
          description: Cinema not found

components:
  schemas:
    Cinema:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        city:
          type: string
        address:
          type: string
        timezone:
          type: string
      required:
      - name
      - city
      - address
      - timezone
    Hall:
      type: object
      properties:
        id:
          type: integer
          format: int64
        cinema:
          type: integer
          format: int64
        name:
          type: string
      required:
      - cinema
      - name
    Seat:
      type: object
      properties:
        id:
          type: integer
          format: int64
        hall:
          type: integer
          format: int64
        x:
          type: integer
          format: int64
        y:
          type: integer
          format: int64
        sector:
          type: integer
          format: int64
      required:
      - hall
      - x
      - y
      - sector
    Tariff:
      type: object
      properties:
        id:
          type: integer
          format: int64
        cinema:
          type: integer
          format: int64
        name:
          type: string
        prices:
          type: array
          items:
            $ref: '#/components/schemas/Price'
      required:
      - cinema
      - name
    Price:
      type: object
      properties:
        id:
          type: integer
          format: int64
        tariff:
          type: integer
          format: int64
        sector:
          type: integer
          format: int64
        price:
          type: integer
          format: int64