# Run
# sudo docker-compose up

version: "2"

services:
  postgresql:
    image: postgres:12
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=cinema
      - POSTGRES_PASSWORD=cinemapass
    # host:container
    ports:
      - "5432:5432"
    networks:
      - test_network
  hall:
    image: cinema-hall
    ports:
      - "8081:8080"
    networks:
      - test_network
    depends_on:
      - postgresql
    links:
      - postgresql

networks:
  test_network:
    driver: bridge
