# Run
# sudo docker-compose up

version: "2"

services:
  postgresql:
    image: postgres:12
    volumes:
      # To re-create base use
      # docker ps -a
      # docker rm <NAME>
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=cinema
      - POSTGRES_PASSWORD=cinemapass
    restart: always
    networks:
      - test_network
  hall:
    image: cinema-hall
    environment:
      - HALLSQL=jdbc:postgresql://postgresql:5432/hall
    ports:
      # host:container
      - "8081:8080"
    networks:
      - test_network
    depends_on:
      - postgresql
    links:
      - postgresql
  session:
    image: cinema-session
    environment:
      - SESSIONSQL=jdbc:postgresql://postgresql:5432/session
    ports:
      # host:container
      - "8082:8080"
    networks:
      - test_network
    depends_on:
      - postgresql
    links:
      - postgresql
  ticket:
    image: cinema-ticket
    environment:
      - TOCKETSQL=jdbc:postgresql://postgresql:5432/ticket
    ports:
      # host:container
      - "8083:8080"
    networks:
      - test_network
    depends_on:
      - postgresql
    links:
      - postgresql
  public:
    image: cinema-public
    environment:
      - HALLHOST=hall
      - HALLPORT=8080
      - SESSIONHOST=session
      - SESSIONPORT=8080
      - TICKETHOST=ticket
      - TICKETPORT=8080
    ports:
      # host:container
      - "8084:8080"
    networks:
      - test_network
    depends_on:
      - hall
      - session
      - ticket
    links:
      - hall
      - session
      - ticket

networks:
  test_network:
    driver: bridge
