# Run
# sudo docker-compose up

version: "2"

services:
  postgresql:
    image: postgres:12
    volumes:
      # Use docker rm if need to re-create
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=cinema
      - POSTGRES_PASSWORD=cinemapass
    restart: always
    networks:
      - test_network
  hall:
    image: cinema-hall
    environment:
      - SQLURL=jdbc:postgresql://postgresql:5432/hall
    ports:
      # host:container
      - "8081:8080"
    networks:
      - test_network
    depends_on:
      - postgresql
    links:
      - postgresql

networks:
  test_network:
    driver: bridge
