openapi: 3.0.0
info:
  title: Cinema API
  description: Cinema API for Administrator
  version: 1.0.0
  contact:
    name: Mikhail Gaidamaka
    url: https://github.com/mgaidamak
    email: magnoly.nsk@gmail.com
servers:
  - url: 'http://localhost:8080'
paths:
  /cinema:
    post:
      summary: Create new cinema
      description: Create new cinema
      operationId: createCinema
      requestBody:
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/Cinema'
      responses:
        200:
          description: Cinema has been created
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Cinema'
    get:
      summary: Get all cinemas
      description: Get all cinemas
      operationId: getCinemas
      parameters:
      - name: city
        in: query
        description: Search at city
        required: false
        schema:
          type: string
      - name: page
        in: query
        description: Offset-based strategy pagination
        schema:
          $ref: '#/components/schemas/Page'
      responses:
        200:
          description: List of cinema
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Cinema'
  /cinema/{id}:
    get:
      summary: Get cinema by ID
      description: Get cinema by ID
      operationId: getCinemaById
      parameters:
      - name: id
        in: path
        description: ID of cinema
        required: true
        schema: 
          type: integer
          format: int32
      responses:
        200:
          description: Cinema associated with ID
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Cinema'
        400:
          description: Invalid id (not Long)
        404:
          description: Cinema not found
    delete:
      summary: Delete cinema by ID
      description: Delete cinema by ID
      operationId: deleteCinemaById
      parameters:
        - name: id
          in: path
          description: ID of cinema
          required: true
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: Previous cinema associated with ID
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Cinema'
        400:
          description: Invalid id (not Long)
        404:
          description: Cinema not found

  /hall:
    post:
      summary: Create new hall
      description: Create new hall
      operationId: createHall
      requestBody:
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/Hall'
      responses:
        200:
          description: Hall has been created
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Hall'
    get:
      summary: Get all halls
      description: Get all halls
      operationId: getHalls
      parameters:
        - name: cinema
          in: query
          description: Search at cinema
          required: true
          schema:
            type: integer
            format: int32
        - name: page
          in: query
          description: Offset-based strategy pagination
          schema:
            $ref: '#/components/schemas/Page'
      responses:
        200:
          description: List of halls
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Hall'
        400:
          description: No cinema parameter
  /hall/{id}:
    get:
      summary: Get hall by ID
      description: Get hall by ID
      operationId: getHallById
      parameters:
        - name: id
          in: path
          description: ID of hall
          required: true
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: Hall associated with ID
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Hall'
        400:
          description: Invalid id (not Long)
        404:
          description: Hall not found
    delete:
      summary: Delete hall by ID
      description: Delete hall by ID
      operationId: deleteHallById
      parameters:
        - name: id
          in: path
          description: ID of hall
          required: true
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: Previous hall associated with ID
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Hall'
        400:
          description: Invalid id (not Long)
        404:
          description: Hall not found

  /seat:
    post:
      summary: Create new seat
      description: Create new seat
      operationId: createSeat
      requestBody:
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/Seat'
      responses:
        200:
          description: Seat has been created
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Seat'
    get:
      summary: Get all seats
      description: Get all seats
      operationId: getSeats
      parameters:
        - name: hall
          in: query
          description: Search at hall
          required: true
          schema:
            type: integer
            format: int32
        - name: page
          in: query
          description: Offset-based strategy pagination
          schema:
            $ref: '#/components/schemas/Page'
      responses:
        200:
          description: List of halls
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Seat'
  /seat/{id}:
    get:
      summary: Get seat by ID
      description: Get seat by ID
      operationId: getSeatById
      parameters:
        - name: id
          in: path
          description: ID of seat
          required: true
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: Seat associated with ID
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Seat'
        400:
          description: Invalid id (not Long)
        404:
          description: Seat not found
    delete:
      summary: Delete seat by ID
      description: Delete seat by ID
      operationId: deleteSeatById
      parameters:
        - name: id
          in: path
          description: ID of seat
          required: true
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: Previous seat associated with ID
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Seat'
        400:
          description: Invalid id (not Long)
        404:
          description: Seat not found

components:
  schemas:
    Cinema:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        city:
          type: string
        address:
          type: string
        timezone:
          type: string
      required:
      - name
      - city
      - address
      - timezone
    Hall:
      type: object
      properties:
        id:
          type: integer
          format: int32
        cinema:
          type: integer
          format: int32
        name:
          type: string
      required:
      - cinema
      - name
    Seat:
      type: object
      properties:
        id:
          type: integer
          format: int32
        hall:
          type: integer
          format: int32
        x:
          type: integer
          format: int32
        y:
          type: integer
          format: int32
      required:
      - hall
      - x
      - y
    Page:
      type: object
      properties:
        offset:
          type: integer
          format: int32
        limit:
          type: integer
          format: int32
